name: CI / Build & Deploy (GitHub Pages)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

# minimum permissions required for Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: github-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test --if-present

      - name: Build app
        run: npm run build

      - name: Upload site build (artifact for Pages)
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # CRA default. For Vite use ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # only deploy for push/workflow_dispatch (skip PRs)
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
